# docker-compose.yml 
version: '3.8'

services:
  backend:
    # build 部分现在包含了多平台构建的配置
    build:
      context: .
      dockerfile: backend.Dockerfile
      platforms:
        - "linux/amd64" # 为 Windows/Intel-Linux 用户构建
        - "linux/arm64" # 为 Apple Silicon/ARM-Linux 用户构建
    
    # image 字段是 buildx 推送的目标，也是本地运行时镜像的名称
    image: niurouxing/hevno-engine-backend:latest
    
    container_name: hevno_backend
    volumes:
      - ./backend:/app/backend
      - ./plugins:/app/plugins
      - ./hevno.json:/app/hevno.json
      - ./cli.py:/app/cli.py
      - ./assets:/app/assets
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./.env:/app/.env.host
    expose:
      - "4399"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4399/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    # build 部分同样配置为多平台
    build:
      context: .
      dockerfile: frontend.Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
        
    # image 字段是 buildx 推送的目标，也是本地运行时镜像的名称
    image: niurouxing/hevno-engine-frontend:latest
    
    container_name: hevno_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - ./plugins:/app/plugins
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - node_modules_volume:/app/node_modules:delegated
    environment:
      - VITE_API_URL=http://backend:4399
    depends_on:
      backend:
        condition: service_healthy

volumes:
  node_modules_volume: