# docker-compose.yml (开发模式)
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: hevno_backend
    volumes:
      - ./backend:/app/backend
      - ./plugins:/app/plugins
      - ./hevno.json:/app/hevno.json
      - ./cli.py:/app/cli.py
      - ./assets:/app/assets
      # [关键] 挂载新创建的入口脚本
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./.env:/app/.env
    # 将后端的 8000 端口暴露给内部网络
    expose:
      - "8000"
    # 添加一个健康检查，让前端可以等待后端真正就绪
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: hevno_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - ./plugins:/app/plugins
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - node_modules_volume:/app/node_modules:delegated
    # [关键] 添加环境变量以告知前端后端的地址
    environment:
      - VITE_API_URL=http://backend:8000
    # [关键] depends_on 现在使用更健壮的 service_healthy 条件
    depends_on:
      backend:
        condition: service_healthy

volumes:
  node_modules_volume: