[tool.pytest.ini_options]
pythonpath = "."
asyncio_mode = "auto"
python_files = "tests/test_*.py"
markers = [
    "llm_gateway: marks tests related to the LLM gateway module",
    "e2e: marks end-to-end tests",
    # 在这里可以添加其他自定义标记
]
