# Hevno/pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hevno-engine"
version = "1.2.0"
authors = [
    { name="Hevno Team", email="contact@example.com" },
]
description = "A dynamically loaded, modular execution engine for Hevno, built with a plugin-first architecture."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# 核心依赖
dependencies = [
    "fastapi",
    "pydantic",
    "pyyaml",
    "pytest",
    "pytest-asyncio",
    "httpx",
]

[project.optional-dependencies]
dev = [ 
    "uvicorn[standard]",
    "typer[all]"
]

[project.scripts]
hevno = "cli:app"

[project.entry-points."hevno.plugins"]
core_logging = "plugins.core_logging"

[tool.setuptools]
include-package-data = true # <-- 使用 MANIFEST.in
py-modules = ["cli"]
# namespace-packages 已被移除

[tool.setuptools.packages.find]
where = ["."]
# `include` 保持不变，它只是告诉 setuptools 去哪里找包，
# 而 Python 如何解释这些包是另一回事。
include = ["backend*", "plugins*"]


# --- Pytest 配置 (已修正) ---
[tool.pytest.ini_options]
# 明确指定测试文件的搜索路径
testpaths = [
    "tests",
    "plugins",
]

# 配置 pytest-asyncio
asyncio_mode = "auto"

markers = [
    "e2e: 标记端到端测试",
]