# Hevno/pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hevno-engine"
version = "1.2.0"
authors = [
    { name="Hevno Team", email="contact@example.com" },
]
description = "A dynamically loaded, modular execution engine for Hevno, built with a plugin-first architecture."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# 核心依赖
dependencies = [
    "fastapi",
    "pydantic",
    "pyyaml",
    "pytest",
    "pytest-asyncio",
    "httpx",
]

[project.optional-dependencies]
dev = [ "uvicorn[standard]" ]

[project.entry-points."hevno.plugins"]
core_logging = "plugins.core_logging"

[tool.setuptools]
namespace-packages = ["plugins"]
[tool.setuptools.packages.find]
where = ["."]
include = ["backend*", "plugins*"]
[tool.setuptools.package-data]
"plugins.*" = ["*.json", "*.yaml"]


# --- Pytest 配置 (已修正) ---
[tool.pytest.ini_options]
# 明确指定测试文件的搜索路径
testpaths = [
    "tests",
    "plugins",
]

# 配置 pytest-asyncio
asyncio_mode = "auto"